### ISSUE TITLE
权限全部允许，但是摄像头还是初始化失败

### ISSUE THREAD

**Issue by silenceyixia** [Liar1995/VideoRecorder#2]

**Comment by Liar1995** [comment]
:sweat: sorry 噢，很久以前写的这个了，你去把CameraActivity.java 文件中467行的固定路径换一下就好了，另外动态权限需要自己处理。

**Comment by silenceyixia** [comment]
oh,yeah,so that's it

**Comment by wusir-china** [comment]
权限全部允许，CameraActivity.java 文件中467行的固定路径也换一下，但是第一次进入录制界面时还是提示摄像头初始化失败。
